// Consulate-specific entry points: which mission's own checklist applies, by country of residence
// and destination. Carried over from the ClearEntry checker's embassy directory (each page found on
// the destination foreign service's own domain; checked 24 September 2026). Each becomes a
// residence-targeted step in the destination's study guide, citing the mission's page.
import type { Guide, Rule, Source } from '../types';
import { MONTHS, step } from './helpers';

interface Mission { res: string; dest: string; mission: string; title: string; url: string }

const MISSIONS: Mission[] = [
  { res: 'IN', dest: 'DE', mission: "German Embassy New Delhi", title: "German Embassy New Delhi: visa information", url: "https://india.diplo.de/in-en/service/-/2341254" },
  { res: 'IN', dest: 'IT', mission: "Embassy of Italy New Delhi", title: "Embassy of Italy New Delhi: visas", url: "https://ambnewdelhi.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'IN', dest: 'IE', mission: "Embassy of Ireland New Delhi", title: "Embassy of Ireland New Delhi: study visa leaflet", url: "https://assets.ireland.ie/documents/20250425_Study_visa_information_leaflet.pdf" },
  { res: 'IN', dest: 'PL', mission: "Embassy of Poland New Delhi", title: "Embassy of Poland New Delhi: visa information", url: "https://newdelhi.mfa.gov.pl/en/consular_information/visa_information/visa_information" },
  { res: 'CN', dest: 'NL', mission: "NetherlandsWorldwide", title: "NetherlandsWorldwide: the Netherlands in China", url: "https://www.netherlandsandyou.nl/your-country-and-the-netherlands/china/travel-and-residence/applying-for-a-short-stay-schengen-visa" },
  { res: 'CN', dest: 'IT', mission: "Embassy of Italy Beijing", title: "Embassy of Italy Beijing: visas", url: "https://ambpechino.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'CN', dest: 'IE', mission: "Embassy of Ireland Beijing", title: "Embassy of Ireland Beijing: visa types and documents", url: "https://www.ireland.ie/en/china/beijing/services/visas/visa-types-documentation/" },
  { res: 'CN', dest: 'SE', mission: "Embassy of Sweden Beijing", title: "Embassy of Sweden Beijing", url: "https://www.swedenabroad.se/en/embassies/china-beijing/" },
  { res: 'US', dest: 'ES', mission: "Consulate of Spain Washington DC", title: "Consulate of Spain Washington DC: study visa", url: "https://www.exteriores.gob.es/Consulados/washington/en/ServiciosConsulares/Paginas/Consular/study-visa.aspx" },
  { res: 'US', dest: 'IT', mission: "Embassy of Italy Washington", title: "Embassy of Italy Washington: visas", url: "https://ambwashingtondc.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'US', dest: 'IE', mission: "Embassy of Ireland USA", title: "Embassy of Ireland USA: visas for Ireland", url: "https://www.ireland.ie/en/usa/washington/services/visas/visas-for-ireland/" },
  { res: 'US', dest: 'PL', mission: "Poland in the US", title: "Poland in the US: D-type national visa", url: "https://www.gov.pl/web/usa-en/d-type-national-visa" },
  { res: 'CA', dest: 'DE', mission: "German Missions in Canada", title: "German Missions in Canada: national visa", url: "https://canada.diplo.de/ca-en/consular-services/visa/long-term" },
  { res: 'CA', dest: 'ES', mission: "Embassy of Spain Ottawa", title: "Embassy of Spain Ottawa: student visa", url: "https://www.exteriores.gob.es/Embajadas/ottawa/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'CA', dest: 'IT', mission: "Embassy of Italy Ottawa", title: "Embassy of Italy Ottawa: national visa for study", url: "https://ambottawa.esteri.it/ambasciata_ottawa/en/informazioni_e_servizi/visti/schengen-or-national-visa-for-study.html" },
  { res: 'CA', dest: 'PL', mission: "Poland in Canada", title: "Poland in Canada: D-type national visa", url: "https://www.gov.pl/web/canada-en/d-type-national-visa" },
  { res: 'AE', dest: 'DE', mission: "German Missions in the UAE", title: "German Missions in the UAE: national visa for study", url: "https://uae.diplo.de/ae-en/service/05-visaeinreise/2490162-2490162" },
  { res: 'AE', dest: 'ES', mission: "Embassy of Spain Abu Dhabi", title: "Embassy of Spain Abu Dhabi: study visa", url: "https://www.exteriores.gob.es/Embajadas/abudhabi/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'AE', dest: 'IT', mission: "Embassy of Italy Abu Dhabi", title: "Embassy of Italy Abu Dhabi: national visa", url: "https://ambabudhabi.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/national-visa/" },
  { res: 'SA', dest: 'DE', mission: "German Embassy Riyadh", title: "German Embassy Riyadh: national visas", url: "https://saudiarabien.diplo.de/ksa-en/visa-service/national-visas-2195264" },
  { res: 'SA', dest: 'IT', mission: "Embassy of Italy Riyadh", title: "Embassy of Italy Riyadh: visas", url: "https://ambriad.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'SA', dest: 'PL', mission: "Poland in Saudi Arabia", title: "Poland in Saudi Arabia: D-type national visa", url: "https://www.gov.pl/web/saudiarabia/d-type-national-visa" },
  { res: 'SA', dest: 'SE', mission: "Embassy of Sweden Riyadh", title: "Embassy of Sweden Riyadh", url: "https://www.swedenabroad.se/en/embassies/saudi-arabia-riyadh/" },
  { res: 'QA', dest: 'DE', mission: "German Embassy Doha", title: "German Embassy Doha: university studies visa", url: "https://doha.diplo.de/qa-en/service/visa/nationale-visa/2583162-2583162" },
  { res: 'QA', dest: 'ES', mission: "Embassy of Spain in Qatar", title: "Embassy of Spain in Qatar", url: "https://www.exteriores.gob.es/Embajadas/doha/en/Paginas/index.aspx" },
  { res: 'QA', dest: 'IT', mission: "Embassy of Italy Doha", title: "Embassy of Italy Doha: visas", url: "https://ambdoha.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'QA', dest: 'PL', mission: "Poland in Qatar", title: "Poland in Qatar: visas", url: "https://www.gov.pl/web/qatar/visas---general-information" },
  { res: 'KW', dest: 'DE', mission: "German Embassy Kuwait", title: "German Embassy Kuwait: student visa (\u00a716b)", url: "https://kuwait.diplo.de/kw-en/service/visa-einreise/2661044-2661044" },
  { res: 'KW', dest: 'IT', mission: "Embassy of Italy Kuwait", title: "Embassy of Italy Kuwait: study", url: "https://ambalkuwait.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/studi/" },
  { res: 'KW', dest: 'PL', mission: "Poland in Kuwait", title: "Poland in Kuwait: student visa documents", url: "https://www.gov.pl/web/kuwait/student-visa-procedure--educational-documents" },
  { res: 'BH', dest: 'FR', mission: "Embassy of France in Bahrain", title: "Embassy of France in Bahrain: applying for a French visa", url: "https://bh.ambafrance.org/Applying-for-a-French-visa-in-Bahrain" },
  { res: 'BH', dest: 'DE', mission: "German Embassy Manama", title: "German Embassy Manama", url: "https://manama.diplo.de/bh-en" },
  { res: 'BH', dest: 'IT', mission: "Embassy of Italy Manama", title: "Embassy of Italy Manama: visas", url: "https://ambmanama.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'OM', dest: 'DE', mission: "German Embassy Muscat", title: "German Embassy Muscat: student visa (\u00a716b)", url: "https://maskat.diplo.de/om-en/service/05-visaeinreise/2609582-2609582" },
  { res: 'OM', dest: 'IT', mission: "Embassy of Italy Muscat", title: "Embassy of Italy Muscat: visas", url: "https://ambmascate.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'DZ', dest: 'FR', mission: "Embassy of France in Algeria", title: "Embassy of France in Algeria: student visas", url: "https://dz.ambafrance.org/Visas-etudiants-delivres-par-les-consulats-generaux-de-France-en-Algerie" },
  { res: 'DZ', dest: 'DE', mission: "German Embassy Algiers", title: "German Embassy Algiers: national visa", url: "https://algier.diplo.de/dz-fr/service/05-visaeinreise/2430460-2430460" },
  { res: 'DZ', dest: 'IT', mission: "Embassy of Italy Algiers", title: "Embassy of Italy Algiers: visas", url: "https://ambalgeri.esteri.it/fr/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'DZ', dest: 'PL', mission: "Poland in Algeria", title: "Poland in Algeria: study visas", url: "https://www.gov.pl/web/algerie/visas-dtudes" },
  { res: 'DZ', dest: 'SE', mission: "Embassy of Sweden Algiers", title: "Embassy of Sweden Algiers", url: "https://www.swedenabroad.se/fr/ambassade/algeriet-alger/" },
  { res: 'CM', dest: 'FR', mission: "Embassy of France in Cameroon", title: "Embassy of France in Cameroon: going to France", url: "https://cm.ambafrance.org/-Visas-Aller-en-France-" },
  { res: 'CM', dest: 'DE', mission: "German Embassy Yaound\u00e9", title: "German Embassy Yaound\u00e9: visas", url: "https://jaunde.diplo.de/cm-fr/service/05-visaeinreise" },
  { res: 'CM', dest: 'ES', mission: "Embassy of Spain Yaound\u00e9", title: "Embassy of Spain Yaound\u00e9: visa appointments", url: "https://www.exteriores.gob.es/Embajadas/yaunde/en/Embajada/Paginas/instructions-visa.aspx" },
  { res: 'CM', dest: 'IT', mission: "Embassy of Italy Yaound\u00e9", title: "Embassy of Italy Yaound\u00e9: study visa", url: "https://ambyaounde.esteri.it/fr/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti__trashed/visto-per-studio/" },
  { res: 'EG', dest: 'DE', mission: "German Embassy Cairo", title: "German Embassy Cairo: study visa (PDF)", url: "https://kairo.diplo.de/resource/blob/2546508/b249cc765b49519705d54e85f137f1d8/merkblatt-eng-studium-data.pdf" },
  { res: 'EG', dest: 'ES', mission: "Embassy of Spain in Egypt", title: "Embassy of Spain in Egypt", url: "https://www.exteriores.gob.es/Embajadas/elcairo/en" },
  { res: 'EG', dest: 'IT', mission: "Embassy of Italy Cairo", title: "Embassy of Italy Cairo: study visa procedure", url: "https://ambilcairo.esteri.it/ar/news/dall_ambasciata/2020/07/richiesta-di-visto-per-studio-immatricolazione-2/" },
  { res: 'EG', dest: 'PL', mission: "Poland in Egypt", title: "Poland in Egypt: D-type national visa", url: "https://www.gov.pl/web/egypt/d-type-national-visa" },
  { res: 'EG', dest: 'SE', mission: "Sweden Abroad (Egypt)", title: "Sweden Abroad (Egypt): apply for a visa", url: "https://www.swedenabroad.se/en/about-sweden-non-swedish-citizens/egypt/going-to-sweden/visiting-sweden/apply-for-a-visa2/" },
  { res: 'GH', dest: 'DE', mission: "German Embassy Accra", title: "German Embassy Accra: visa for students", url: "https://accra.diplo.de/gh-en/service/-visainformation/2615324-2615324" },
  { res: 'GH', dest: 'IT', mission: "Embassy of Italy Accra", title: "Embassy of Italy Accra: Declaration of Value requirements (PDF)", url: "https://ambaccra.esteri.it/wp-content/uploads/2024/05/Requisiti-Dichiarazione-di-Valore.pdf" },
  { res: 'KE', dest: 'DE', mission: "German Embassy Nairobi", title: "German Embassy Nairobi: visa for higher education studies", url: "https://nairobi.diplo.de/ke-en/service/visa-entry/2629250-2629250" },
  { res: 'KE', dest: 'IT', mission: "Embassy of Italy Nairobi", title: "Embassy of Italy Nairobi: studies", url: "https://ambnairobi.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/studiare-in-italia/" },
  { res: 'KE', dest: 'PL', mission: "Poland in Kenya", title: "Poland in Kenya: D-type national visa", url: "https://www.gov.pl/web/kenya/d-type-national-visa" },
  { res: 'MA', dest: 'DE', mission: "German Embassy Rabat", title: "German Embassy Rabat: study visa", url: "https://rabat.diplo.de/ma-fr/service/visa-einreise/2732202-2732202" },
  { res: 'MA', dest: 'ES', mission: "Embassy of Spain Rabat", title: "Embassy of Spain Rabat: student visa", url: "https://www.exteriores.gob.es/Embajadas/rabat/fr/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'MA', dest: 'PL', mission: "Poland in Morocco", title: "Poland in Morocco: national (D) visa", url: "https://www.gov.pl/web/maroc/un-visa-national-type-d" },
  { res: 'NG', dest: 'DE', mission: "German Missions in Nigeria", title: "German Missions in Nigeria: university studies visa", url: "https://nigeria.diplo.de/ng-en/2750690-2750690" },
  { res: 'NG', dest: 'IT', mission: "Embassy of Italy Abuja", title: "Embassy of Italy Abuja: visas", url: "https://ambabuja.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'NG', dest: 'IE', mission: "Embassy of Ireland Nigeria", title: "Embassy of Ireland Nigeria: visa processing times", url: "https://www.ireland.ie/en/nigeria/abuja/services/visas/weekly-decision-reports/" },
  { res: 'NG', dest: 'PL', mission: "Poland in Nigeria", title: "Poland in Nigeria: D-type national visa", url: "https://www.gov.pl/web/nigeria-en/d-type-national-visa" },
  { res: 'NG', dest: 'SE', mission: "Embassy of Sweden Abuja", title: "Embassy of Sweden Abuja", url: "https://www.swedenabroad.se/en/embassies/nigeria-abuja/" },
  { res: 'SN', dest: 'FR', mission: "Embassy of France in Senegal", title: "Embassy of France in Senegal: study in France", url: "https://sn.ambafrance.org/Etudier-en-France" },
  { res: 'SN', dest: 'DE', mission: "German Embassy Dakar", title: "German Embassy Dakar: visas", url: "https://dakar.diplo.de/sn-en/service/visa" },
  { res: 'SN', dest: 'PL', mission: "Poland in Senegal", title: "Poland in Senegal: national (D) visa", url: "https://www.gov.pl/web/senegal-fr/un-visa-national-type-d" },
  { res: 'ZA', dest: 'DE', mission: "German Missions in South Africa", title: "German Missions in South Africa: study visa", url: "https://southafrica.diplo.de/sa-en/sa-consular/sa-studyvisa-498290" },
  { res: 'ZA', dest: 'ES', mission: "Embassy of Spain Pretoria", title: "Embassy of Spain Pretoria: study visa", url: "https://www.exteriores.gob.es/Embajadas/pretoria/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'ZA', dest: 'IE', mission: "Embassy of Ireland South Africa", title: "Embassy of Ireland South Africa: visas for Ireland", url: "https://www.ireland.ie/en/southafrica/pretoria/services/visas/visas-for-ireland/" },
  { res: 'ZA', dest: 'PL', mission: "Poland in South Africa", title: "Poland in South Africa: student visa information", url: "https://www.gov.pl/web/southafrica/booking-appointment-date" },
  { res: 'TN', dest: 'DE', mission: "German Embassy Tunis", title: "German Embassy Tunis: study visa", url: "https://tunis.diplo.de/tn-fr/service/05-visaeinreise/2573172-2573172" },
  { res: 'TN', dest: 'ES', mission: "Embassy of Spain Tunis", title: "Embassy of Spain Tunis: student visa", url: "https://www.exteriores.gob.es/Embajadas/tunez/fr/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'TN', dest: 'IT', mission: "Embassy of Italy Tunis", title: "Embassy of Italy Tunis: study visa (PDF)", url: "https://ambtunisi.esteri.it/wp-content/uploads/2023/10/visa_etudes.pdf" },
  { res: 'TN', dest: 'PL', mission: "Poland in Tunisia", title: "Poland in Tunisia: national (D) visa", url: "https://www.gov.pl/web/tunisie/un-visa-national-type-d" },
  { res: 'TN', dest: 'SE', mission: "Embassy of Sweden Tunis", title: "Embassy of Sweden Tunis", url: "https://www.swedenabroad.se/fr/ambassade/tunisie-tunis/" },
  { res: 'BD', dest: 'DE', mission: "German Embassy Dhaka", title: "German Embassy Dhaka: study visa information", url: "https://dhaka.diplo.de/bd-en/service/2685884-2685884" },
  { res: 'BD', dest: 'ES', mission: "Embassy of Spain Dhaka", title: "Embassy of Spain Dhaka: study visa", url: "https://www.exteriores.gob.es/Embajadas/dhaka/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'ID', dest: 'NL', mission: "Netherlands in Indonesia", title: "Netherlands in Indonesia: MVV visa for students", url: "https://www.netherlandsandyou.nl/web/indonesia/w/mvv-visa-for-students" },
  { res: 'ID', dest: 'IT', mission: "Embassy of Italy Jakarta", title: "Embassy of Italy Jakarta: study in Italy", url: "https://ambjakarta.esteri.it/en/italia-e-indonesia/diplomazia-culturale/studiare-in-italia/" },
  { res: 'ID', dest: 'PL', mission: "Poland in Indonesia", title: "Poland in Indonesia: study visa message", url: "https://www.gov.pl/web/indonesia-en/study-visa---important-message-for-students" },
  { res: 'ID', dest: 'SE', mission: "Embassy of Sweden Jakarta", title: "Embassy of Sweden Jakarta", url: "https://www.swedenabroad.se/en/embassies/indonesia-jakarta/" },
  { res: 'IR', dest: 'ES', mission: "Embassy of Spain in Iran", title: "Embassy of Spain in Iran: consular services", url: "https://www.exteriores.gob.es/Embajadas/teheran/en/ServiciosConsulares/Paginas/inicio.aspx" },
  { res: 'IR', dest: 'IT', mission: "Embassy of Italy", title: "Embassy of Italy: visa applications for Iranian citizens (May 2026)", url: "https://ambmascate.esteri.it/en/news/dall_ambasciata/2026/05/visa-application-for-iranian-citizens/" },
  { res: 'IR', dest: 'IE', mission: "Embassy of Ireland, Iran", title: "Embassy of Ireland, Iran", url: "https://www.ireland.ie/en/tehran/" },
  { res: 'IR', dest: 'PL', mission: "Poland in Iran", title: "Poland in Iran: D-type national visa", url: "https://www.gov.pl/web/iran-en/d-type-national-visa" },
  { res: 'IR', dest: 'SE', mission: "Embassy of Sweden Tehran", title: "Embassy of Sweden Tehran", url: "https://www.swedenabroad.se/en/embassies/iran-tehran/" },
  { res: 'JP', dest: 'DE', mission: "German Embassy Tokyo", title: "German Embassy Tokyo: study in Germany visa", url: "https://japan.diplo.de/ja-ja/service/study/908722" },
  { res: 'JP', dest: 'ES', mission: "Embassy of Spain Tokyo", title: "Embassy of Spain Tokyo: study visa", url: "https://www.exteriores.gob.es/Embajadas/tokio/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'JP', dest: 'IT', mission: "Embassy of Italy Tokyo", title: "Embassy of Italy Tokyo: visas", url: "https://ambtokyo.esteri.it/ja/servizi-consolari-e-visti/visti/" },
  { res: 'JP', dest: 'PL', mission: "Poland in Japan", title: "Poland in Japan: D-type national visa", url: "https://www.gov.pl/web/nippon/d-type-national-visa" },
  { res: 'MY', dest: 'DE', mission: "German Embassy Kuala Lumpur", title: "German Embassy Kuala Lumpur: student visa", url: "https://kuala-lumpur.diplo.de/my-en/service/05-visaeinreise/2284850-2284850" },
  { res: 'MY', dest: 'IT', mission: "Embassy of Italy Kuala Lumpur", title: "Embassy of Italy Kuala Lumpur: university enrolment visa (PDF)", url: "https://ambkualalumpur.esteri.it/wp-content/uploads/2026/07/STUDY-UNIVERSITY-ENROLLMENT.pdf" },
  { res: 'NP', dest: 'DE', mission: "German Embassy Kathmandu", title: "German Embassy Kathmandu: study visa", url: "https://kathmandu.diplo.de/np-en/service/01-visaeinreise/2225320-2225320" },
  { res: 'PK', dest: 'DE', mission: "German Mission in Pakistan", title: "German Mission in Pakistan: study visa", url: "https://pakistan.diplo.de/pk-en/service/2-study-visa-seite/1676104" },
  { res: 'PK', dest: 'IT', mission: "Embassy of Italy Islamabad", title: "Embassy of Italy Islamabad: visas", url: "https://ambislamabad.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'PK', dest: 'PL', mission: "Poland in Pakistan", title: "Poland in Pakistan: D-type national visa", url: "https://www.gov.pl/web/pakistan-en/d-type-national-visa" },
  { res: 'PH', dest: 'DE', mission: "German Embassy Manila", title: "German Embassy Manila: long-stay national visa", url: "https://manila.diplo.de/ph-en/service/visa/2439020-2439020" },
  { res: 'PH', dest: 'IT', mission: "Embassy of Italy Manila", title: "Embassy of Italy Manila: study visa", url: "https://ambmanila.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/study-visa/" },
  { res: 'PH', dest: 'PL', mission: "Poland in the Philippines", title: "Poland in the Philippines: D-type national visa", url: "https://www.gov.pl/web/philippines/d-type-national-visa" },
  { res: 'KR', dest: 'DE', mission: "German Embassy Seoul", title: "German Embassy Seoul: study visa", url: "https://seoul.diplo.de/kr-ko/service/06-visaeng/1891982-1891982" },
  { res: 'KR', dest: 'ES', mission: "Embassy of Spain Seoul", title: "Embassy of Spain Seoul: student visa", url: "https://www.exteriores.gob.es/Embajadas/seul/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'KR', dest: 'SE', mission: "Embassy of Sweden Seoul", title: "Embassy of Sweden Seoul", url: "https://www.swedenabroad.se/en/embassies/south-korea-seoul/" },
  { res: 'LK', dest: 'DE', mission: "German Embassy Colombo", title: "German Embassy Colombo: national visa", url: "https://colombo.diplo.de/lk-en/service/01-visaeinreisenational" },
  { res: 'LK', dest: 'IT', mission: "Embassy of Italy Colombo", title: "Embassy of Italy Colombo: visas", url: "https://ambcolombo.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'VN', dest: 'DE', mission: "German Embassy Hanoi", title: "German Embassy Hanoi: visa for studies", url: "https://vietnam.diplo.de/vn-de/service/2306542-2306542" },
  { res: 'VN', dest: 'ES', mission: "Embassy of Spain Hanoi", title: "Embassy of Spain Hanoi: national visa for study (PDF)", url: "https://www.exteriores.gob.es/DocumentosAuxiliaresSC/Vietnam/HANOI%20(E)/21c%20Nacionales.%20Estudios%20(EN).pdf" },
  { res: 'VN', dest: 'IT', mission: "Embassy of Italy Hanoi", title: "Embassy of Italy Hanoi: pre-enrolment and student visas", url: "https://ambhanoi.esteri.it/en/italia-e-vietnam/diplomazia-culturale/studiare-in-italia/pre-enrollments-and-student-visas/" },
  { res: 'VN', dest: 'IE', mission: "Embassy of Ireland Vietnam", title: "Embassy of Ireland Vietnam: contact", url: "https://www.ireland.ie/en/vietnam/hanoi/contact/" },
  { res: 'VN', dest: 'SE', mission: "Embassy of Sweden Hanoi", title: "Embassy of Sweden Hanoi", url: "https://www.swedenabroad.se/en/embassies/vietnam-hanoi/" },
  { res: 'KZ', dest: 'DE', mission: "German Embassy Astana", title: "German Embassy Astana: national visas", url: "https://kasachstan.diplo.de/kz-de/2012022-2012022" },
  { res: 'KZ', dest: 'PL', mission: "Polish consulate Astana", title: "Polish consulate Astana: e-Konsulat registration", url: "https://secure.e-konsulat.gov.pl/placowki/140" },
  { res: 'RU', dest: 'DE', mission: "German Missions in Russia", title: "German Missions in Russia: general visa information", url: "https://germania.diplo.de/ru-de/service/05-visaeinreise/1623820-1623820" },
  { res: 'RU', dest: 'NL', mission: "Netherlands Embassy in Moscow", title: "Netherlands Embassy in Moscow: contact", url: "https://www.netherlandsandyou.nl/web/russian-federation/about-us/contact-embassy-moscow" },
  { res: 'RU', dest: 'IE', mission: "Embassy of Ireland Russia", title: "Embassy of Ireland Russia: visas for Ireland", url: "https://www.ireland.ie/en/moscow/services/visas/visas-for-ireland/" },
  { res: 'RU', dest: 'PL', mission: "Polish consulate Moscow", title: "Polish consulate Moscow: e-Konsulat registration", url: "https://secure.e-konsulat.gov.pl/placowki/82" },
  { res: 'RU', dest: 'SE', mission: "Sweden Abroad (Russia)", title: "Sweden Abroad (Russia): apply for a visa", url: "https://www.swedenabroad.se/en/about-sweden-non-swedish-citizens/russia/going-to-sweden/travelling-to-sweden/apply-for-a-visa/" },
  { res: 'TR', dest: 'DE', mission: "German Missions in T\u00fcrkiye", title: "German Missions in T\u00fcrkiye: study visas", url: "https://tuerkei.diplo.de/tr-de/service/05-visaeinreise/2616402-2616402" },
  { res: 'TR', dest: 'NL', mission: "NetherlandsWorldwide", title: "NetherlandsWorldwide: MVV in T\u00fcrkiye", url: "https://www.netherlandsandyou.nl/your-country-and-the-netherlands/turkey/travel-and-residence/applying-for-a-long-stay-visa-mvv" },
  { res: 'TR', dest: 'ES', mission: "Embassy of Spain Ankara", title: "Embassy of Spain Ankara: study visa", url: "https://www.exteriores.gob.es/Embajadas/ankara/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=Turqu%C3%ADa&scd=12&scs=Visados+Nacionales+-+Visado+de+estudios" },
  { res: 'TR', dest: 'IE', mission: "Embassy of Ireland T\u00fcrkiye", title: "Embassy of Ireland T\u00fcrkiye: visas for Ireland", url: "https://www.ireland.ie/en/turkiye/ankara/services/visas/visas-for-ireland/" },
  { res: 'TR', dest: 'SE', mission: "Embassy of Sweden Ankara", title: "Embassy of Sweden Ankara: contact", url: "https://www.swedenabroad.se/en/embassies/turkey-ankara/contact/" },
  { res: 'UA', dest: 'DE', mission: "German Embassy Kyiv", title: "German Embassy Kyiv: visa information in English", url: "https://ukraine.diplo.de/ua-de/service/05-visaeinreise/2305172-2305172" },
  { res: 'UA', dest: 'NL', mission: "Netherlands Embassy in Kyiv", title: "Netherlands Embassy in Kyiv", url: "https://www.netherlandsandyou.nl/your-country-and-the-netherlands/ukraine/about-us/embassy-in-kyiv" },
  { res: 'UA', dest: 'IE', mission: "Embassy of Ireland Ukraine", title: "Embassy of Ireland Ukraine: visas", url: "https://www.ireland.ie/en/kyiv/visas/" },
  { res: 'UA', dest: 'SE', mission: "Sweden Abroad (Ukraine)", title: "Sweden Abroad (Ukraine): how to apply", url: "https://www.swedenabroad.se/en/about-sweden-non-swedish-citizens/ukraine/going-to-sweden/visiting-sweden/apply-for-a-visa/" },
  { res: 'GB', dest: 'DE', mission: "German Embassy London", title: "German Embassy London: D-visa for university studies", url: "https://uk.diplo.de/uk-en/02/university-studies-2449178" },
  { res: 'GB', dest: 'ES', mission: "Consulate General of Spain London", title: "Consulate General of Spain London: study visa", url: "https://www.exteriores.gob.es/Consulados/londres/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'GB', dest: 'IT', mission: "Consulate General of Italy London", title: "Consulate General of Italy London: study visa", url: "https://conslondra.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/study/" },
  { res: 'GB', dest: 'PL', mission: "Poland in the UK", title: "Poland in the UK: D-type national visa", url: "https://www.gov.pl/web/unitedkingdom/d-type-national-visa" },
  { res: 'UZ', dest: 'DE', mission: "German Embassy Tashkent", title: "German Embassy Tashkent: study visa", url: "https://taschkent.diplo.de/uz-de/service/05-visaeinreise/2445770-2445770" },
  { res: 'UZ', dest: 'IT', mission: "Embassy of Italy Tashkent", title: "Embassy of Italy Tashkent: visas", url: "https://ambtashkent.esteri.it/it/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
  { res: 'AR', dest: 'DE', mission: "German Embassy Buenos Aires", title: "German Embassy Buenos Aires: study visa", url: "https://buenos-aires.diplo.de/ar-es/service/visa-einreise/visadeestudio-2194872" },
  { res: 'AR', dest: 'ES', mission: "Consulate General of Spain Buenos Aires", title: "Consulate General of Spain Buenos Aires: study visa", url: "https://www.exteriores.gob.es/Consulados/buenosaires/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=Argentina&scd=40&scs=Visados+Nacionales+-+Visado+de+estudios" },
  { res: 'AR', dest: 'IT', mission: "Consulate General of Italy Buenos Aires", title: "Consulate General of Italy Buenos Aires: 2026/27 study visa guidance", url: "https://consbuenosaires.esteri.it/it/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/studenti-internazionali-nuove-indicazioni-su-visto-e-immatricolazione-per-gli-anni-accademici-2026-2027-e-2027-2028/" },
  { res: 'AU', dest: 'DE', mission: "German Missions in Australia", title: "German Missions in Australia: student visa", url: "https://australien.diplo.de/au-en/service/visa/long-term/study-2640466" },
  { res: 'AU', dest: 'ES', mission: "Embassy of Spain Canberra", title: "Embassy of Spain Canberra: study visa", url: "https://www.exteriores.gob.es/Embajadas/canberra/en/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'AU', dest: 'IT', mission: "Consulate General of Italy Melbourne", title: "Consulate General of Italy Melbourne: long-stay student visa", url: "https://consmelbourne.esteri.it/en/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/italian-and-shengen-area-visas/national-visas-from-91-to-365-days-in-italy/visti-studio-lungo-soggiorno/" },
  { res: 'BR', dest: 'DE', mission: "German Missions in Brazil", title: "German Missions in Brazil: study visa", url: "https://brasil.diplo.de/br-pt/servicos/vistos/estudo-2568248" },
  { res: 'BR', dest: 'ES', mission: "Embassy of Spain Bras\u00edlia", title: "Embassy of Spain Bras\u00edlia: study visa", url: "https://www.exteriores.gob.es/Embajadas/brasilia/pt/ServiciosConsulares/Paginas/Consular/Visado-de-estudios.aspx" },
  { res: 'BR', dest: 'IT', mission: "Embassy of Italy Bras\u00edlia", title: "Embassy of Italy Bras\u00edlia: long-stay (D) visas", url: "https://ambbrasilia.esteri.it/pt/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/visto-di-lunga-durata-tipo-d/tipi-di-visto-di-lunga-durata-tipo-d/" },
  { res: 'BR', dest: 'PL', mission: "Poland in Brazil", title: "Poland in Brazil: national (D) visa", url: "https://www.gov.pl/web/brasil/um-visto-nacional-tipo-d" },
  { res: 'CL', dest: 'DE', mission: "German Embassy Santiago", title: "German Embassy Santiago: university study visa", url: "https://santiago.diplo.de/cl-es/service/05-visaeinreise/2494130-2494130" },
  { res: 'CL', dest: 'ES', mission: "Consulate General of Spain Santiago", title: "Consulate General of Spain Santiago: study visa", url: "https://www.exteriores.gob.es/Consulados/santiagodechile/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=Chile&scd=260&scs=Visados+Nacionales+-+Visado+de+estudios" },
  { res: 'CL', dest: 'IE', mission: "Embassy of Ireland Chile", title: "Embassy of Ireland Chile: visas", url: "https://www.ireland.ie/en/chile/santiago/services/visas/" },
  { res: 'CO', dest: 'DE', mission: "German Embassy Bogot\u00e1", title: "German Embassy Bogot\u00e1: national visas", url: "https://bogota.diplo.de/co-es/service/visa-einreise/1808586-1808586" },
  { res: 'CO', dest: 'ES', mission: "Consulate General of Spain Bogot\u00e1", title: "Consulate General of Spain Bogot\u00e1: study visa", url: "https://www.exteriores.gob.es/Consulados/bogota/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=Colombia&scd=31&scs=Visados+Nacionales+-+Visado+de+estudios" },
  { res: 'CO', dest: 'IT', mission: "Embassy of Italy Bogot\u00e1", title: "Embassy of Italy Bogot\u00e1: university enrolment study visa", url: "https://ambbogota.esteri.it/es/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/visas-requisitos/visas-de-estudio/visa-de-estudio-para-la-inscripcion-en-una-universidad-operante-en-italia/" },
  { res: 'CO', dest: 'IE', mission: "Embassy of Ireland Colombia", title: "Embassy of Ireland Colombia: visas for Ireland", url: "https://www.ireland.ie/en/colombia/bogota/services/visas/visas-for-ireland/" },
  { res: 'MX', dest: 'DE', mission: "German Embassy Mexico City", title: "German Embassy Mexico City: long-stay visas", url: "https://mexiko.diplo.de/mx-es/servicios/visa/visaestancialarga/1047218" },
  { res: 'MX', dest: 'ES', mission: "Consulate General of Spain Mexico City", title: "Consulate General of Spain Mexico City: study visa", url: "https://www.exteriores.gob.es/Consulados/mexico/es/ServiciosConsulares/Paginas/index.aspx?scca=Visados&scco=M%C3%A9xico&scd=195&scs=Visados+Nacionales+-+Visado+de+estudios" },
  { res: 'MX', dest: 'IT', mission: "Embassy of Italy Mexico City", title: "Embassy of Italy Mexico City: visas", url: "https://ambcittadelmessico.esteri.it/es/servizi-consolari-e-visti/servizi-per-il-cittadino-straniero/visti/" },
];

export const MISSION_SOURCES: Record<string, Source> = Object.fromEntries(MISSIONS.map((m) => [
  `mission-${m.dest.toLowerCase()}-${m.res.toLowerCase()}`,
  { kind: 'official', publisher: m.mission, published: 'n.d.', title: m.title, url: m.url } satisfies Source,
]));

function missionRule(m: Mission): Rule {
  return step(`mission-${m.res.toLowerCase()}`, `Follow the checklist of the ${m.mission}`,
    [`mission-${m.dest.toLowerCase()}-${m.res.toLowerCase()}`], 'official', {
      for: { residenceIn: [m.res] }, due: MONTHS(4),
      detail: 'This mission handles applications from the applicant\'s country of residence. Its own document list, fees in local currency and appointment rules take precedence over general guidance.',
    });
}

/** Adds the mission steps to the matching study guides. */
export function withMissions(guides: Guide[]): Guide[] {
  return guides.map((g) => {
    if (g.route !== 'study') return g;
    const extra = MISSIONS.filter((m) => m.dest === g.destination).map(missionRule);
    return extra.length ? { ...g, rules: [...g.rules, ...extra] } : g;
  });
}
